name: Production Deployment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install and setup Node version
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"
          cache: "npm"
      - name: Setup the AWS Cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: AKIAR6FRLN2AMCZ7IXCP
          aws-secret-access-key: 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
      - run: yarn install
      - run: NODE_ENV=production yarn build --if-present
      - run: aws s3 sync . s3://insignia-backend/ --quiet --delete
